### ISSUE TITLE
[bug] install_vulkan.py / uninstall.sh attempts to remove /usr/lib/local/cmake

### ISSUE THREAD

**Issue by tmpvar** [KhronosGroup/MoltenVK#880]
This directory is used by homebrew and when attempting to run `install_vulkan.py` it exits with error:

```
Copying /Users/tmpvar/work/vulkansdk-macos-1.2.135.0/macOS/lib/cmake to /usr/local/lib/cmake
Traceback (most recent call last):
  File "install_vulkan.py", line 159, in <module>
    main()
  File "install_vulkan.py", line 153, in main
    shutil.rmtree(absolute_copy_files[key]["Dest"])
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 273, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/cmake/embree-2.7.1/embree-config.cmake'
```
**note**: INSTALL.log does not include this error

where the (truncated) contents of `/usr/lib/local/cmake` on my machine looks like: 

```
‣ ls -alh /usr/local/lib/cmake
total 0
drwxr-xr-x  64 tmpvar 2.0K May 20 12:49 .
drwxr-xr-x 941 tmpvar  30K May 20 12:49 ..
lrwxr-xr-x   1 tmpvar   48 Jan 20 20:02 Boost-1.72.0 -> ../../Cellar/boost/1.72.0/lib/cmake/Boost-1.72.0
lrwxr-xr-x   1 tmpvar   53 Feb 22  2016 BoostCompute -> ../../Cellar/boost-compute/0.5/lib/cmake/BoostCompute
lrwxr-xr-x   1 tmpvar   67 Jan 20 20:02 BoostDetectToolset-1.72.0.cmake -> ../../Cellar/boost/1.72.0/lib/cmake/BoostDetectToolset-1.72.0.cmake
lrwxr-xr-x   1 tmpvar   46 Mar 26 14:19 FreeGLUT -> ../../Cellar/freeglut/3.2.1/lib/cmake/FreeGLUT
lrwxr-xr-x   1 tmpvar   44 Mar 26 14:19 IlmBase -> ../../Cellar/ilmbase/2.4.1/lib/cmake/IlmBase
lrwxr-xr-x   1 tmpvar   61 Feb 27 17:15 LeptonicaConfig.cmake -> ../../Cellar/leptonica/1.79.0/lib/cmake/LeptonicaConfig.cmake
lrwxr-xr-x   1 tmpvar   44 Mar 26 14:21 OpenEXR -> ../../Cellar/openexr/2.4.1/lib/cmake/OpenEXR
lrwxr-xr-x   1 tmpvar   39 Mar 26 14:24 SDL2 -> ../../Cellar/sdl2/2.0.12/lib/cmake/SDL2
lrwxr-xr-x   1 tmpvar   42 Feb 27 17:15 Snappy -> ../../Cellar/snappy/1.1.8/lib/cmake/Snappy
lrwxr-xr-x   1 tmpvar   40 Mar 26 14:20 TBB -> ../../Cellar/tbb/2020_U1_1/lib/cmake/TBB
lrwxr-xr-x   1 tmpvar   46 Feb 27 17:17 assimp-5.0 -> ../../Cellar/assimp/5.0.1/lib/cmake/assimp-5.0
...
drwxr-xr-x   4 root    128 Nov 14  2015 embree-2.7.1
...
```

So now that I'm in a half-installed state; attempting to back out by running `uninstall.sh` removes all of the symlinks, that has permission to, in the `/usr/lib/local/cmake` directory.

```
‣ ./uninstall.sh
Removing /usr/local/bin/spirv-reduce
Removing /usr/local/lib/libspirv-cross-util.a
Removing /usr/local/lib/libspirv-cross-reflect.a
Removing /usr/local/bin/spirv-dis
...
Removing /usr/local/lib/libOSDependent.a
Removing /usr/local/lib/cmake
rm: /usr/local/lib/cmake/embree-2.7.1/embree-config.cmake: Permission denied
rm: /usr/local/lib/cmake/embree-2.7.1/embree-config-version.cmake: Permission denied
rm: /usr/local/lib/cmake/embree-2.7.1: Directory not empty
rm: /usr/local/lib/cmake: Directory not empty
...
```
leaving the contents of the directory looking like:

```
‣  ls -alh /usr/local/lib/cmake
drwxr-xr-x   4 root   128 Nov 14  2015 embree-2.7.1
```

**Comment by billhollings** [comment]
Sorry for the delay in looking at this. 

This looks to be an SDK issue. I'm going to close this issue here. If this issue is still occurring, please post to the [Vulkan SDK issues list](https://vulkan.lunarg.com/issue/home).
